import type { Metadata } from "next";
import { Nanum_Gothic, Chewy } from "next/font/google";
import "./globals.css";

const nanumGothic = Nanum_Gothic({
  variable: "--font-nanum-gothic",
  weight: ["400", "800"],
});

const chewy = Chewy({
  variable: "--font-chewy",
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nanumGothic.variable} ${chewy.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
